### ISSUE TITLE
Current version was improperly published / wrong docs

### ISSUE THREAD

**Issue by dpopp07** [IBM/schematics-node-sdk#6]
**Describe the bug**

When I install this SDK, the published folder structure is improperly formatted and doesn't even come close to the documentation in terms of how it can be used. There are a couple of issues; I'll capture both individually.

1) The published file structure is wrong. The package should be published _from_ the `dist` directory but it seems to have been published from the root directory and _includes_ the `dist` directory. See my screenshot of the published file structure below. It also includes a bunch of other files and such that do not belong in the published package like config files, etc.

2) The docs in the README do not match the [Cloud docs](https://cloud.ibm.com/apidocs/schematics/schematics?code=node). Neither of them are correct for the currently published structure. Once the structure is fixed, however, the docs should be made to match. The README is more correct in terms of what it _should_ be. The Cloud docs have all sorts of issues.

For example, the [README](https://github.com/IBM/schematics-node-sdk#overview) gives the import path: `@ibm-cloud/ibm-schematics/schematics/v1`.

The Cloud docs show the import as `const { SchematicsV1 } = require('@ibm-cloud/schematics');`

It would be useful to show a proper import (`const SchematicsV1 = require('@ibm-cloud/ibm-schematics/schematics/v1');`) in [this example](https://github.com/IBM/schematics-node-sdk#getting-started).

**To Reproduce**
List the steps that can be used to demonstrate the bug.  Include the name of the service and operation that you're trying to invoke, if applicable.  Be sure to describe any relevant info regarding parameter values used with your API invocation.

1) Create a new test directory and install the SDK
```
$ mkdir node-schematics-test
$ npm init -y
$ npm install "@ibm-cloud/ibm-schematics"
```

2) Create a file, `index.js`, with the following code:
```js
const SchematicsV1 = require('@ibm-cloud/ibm-schematics/schematics/v1');
const { NoAuthAuthenticator } = require('@ibm-cloud/ibm-schematics/auth');

const authenticator = new NoAuthAuthenticator();

const service = new SchematicsV1({
    authenticator,
});
```

3) Run the code
```
$ node index.js
```

**Expected behavior**

The code should run cleanly, with no errors or output. Instead, there is an exception:
`Error: Cannot find module '@ibm-cloud/ibm-schematics/schematics/v1'`

**Screenshots**
<img width="445" alt="Screenshot 2023-05-09 at 11 07 44 AM" src="https://github.com/IBM/schematics-node-sdk/assets/9168931/9ced0e83-e5dc-4095-bb4f-f91f8e75e755">

**Must gather (please complete the following information):**
 - SDK Version 2.0.0
 - Node Version 16.16.0

**Additional context**
Were you able to avoid the problem by changing your application code slightly?

**Comment by VishwaKumar** [comment]
Latest version [2.0.3](https://www.npmjs.com/package/@ibm-cloud/ibm-schematics/v/2.0.3) is published with fixes. Hence closing the issue
